name: Run just ci
description: Install required tools and run `just ci`
runs:
  using: composite
  steps:
    - name: Install just
      uses: taiki-e/install-action@b9c5db3aef04caffaf95a1d03931de10fb2a140f # v2.65.1
      with:
        tool: just

    - name: Install Zola
      uses: taiki-e/install-action@b9c5db3aef04caffaf95a1d03931de10fb2a140f # v2.65.1
      with:
        tool: zola@0.21.0

    # We intentionally install actionlint from the official GitHub release tarball to avoid relying
    # on additional third-party actions.
    - name: Install actionlint
      shell: bash
      run: |
        set -euo pipefail

        ACTIONLINT_VERSION="1.7.9"
        case "$(uname -m)" in
          x86_64) ACTIONLINT_ARCH="amd64" ;;
          aarch64|arm64) ACTIONLINT_ARCH="arm64" ;;
          *) echo "Unsupported arch: $(uname -m)"; exit 1 ;;
        esac

        curl -fsSL \
          -o /tmp/actionlint.tar.gz \
          "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_linux_${ACTIONLINT_ARCH}.tar.gz"

        # Verify checksum for integrity
        case "${ACTIONLINT_ARCH}" in
          amd64)
            echo "233b280d05e100837f4af1433c7b40a5dcb306e3aa68fb4f17f8a7f45a7df7b4  /tmp/actionlint.tar.gz" | sha256sum -c -
            ;;
          arm64)
            echo "6b82a3b8c808bf1bcd39a95aced22fc1a026eef08ede410f81e274af8deadbbc  /tmp/actionlint.tar.gz" | sha256sum -c -
            ;;
        esac

        tar -xzf /tmp/actionlint.tar.gz -C /tmp actionlint
        sudo install -m 0755 /tmp/actionlint /usr/local/bin/actionlint
        actionlint -version

    - name: Install uv
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
      with:
        version: "0.9.18"

    - name: Verify Node.js (for npx tools)
      shell: bash
      run: |
        set -euo pipefail
        node --version
        npx --version

    - name: Run CI checks
      shell: bash
      run: just ci
