name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: >
    ci-${{ github.workflow }}-${{
      github.event_name == 'pull_request' &&
      github.event.pull_request.number ||
      github.ref
    }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          submodules: recursive

      - name: Run CI checks
        uses: ./.github/actions/run-just-ci
